### PR TITLE
Filename string update 

### PR DESCRIPTION
**Pull request by yoanhg421**
Updated filename string to resemble the metadata
filename [1/3]
When sending book using the SendToKindle Service filename still says "PART_1" which doesn't tell us the total parts
SendToKindle doesn't seem to read the title from the metadata.

### CODE REVIEW

**Comment by celogeek** [comment]
The filename may differ from the title as both are separate parameter.
By default, if omit, output will take the name of the input.

The output with your patch have suffix [X_Y]
The title have suffix [X/Y]

May be we can be a bit more explicit on the filename ?

like: OUTPUT Part X of Y.
And also keep the %02d for keeping the sort correct, specially if you have more that 9 part.

**Review by celogeek — CHANGES_REQUESTED** [review]
please rebase your branch from master, so I can do a merge instead of cherry-picking.
also reflect this change in the README (lookup for PART_)

**Comment by celogeek** [comment]
A lot of people complain about title and author when sending to kindle.
Now we can omit "Author" with the app, and it will pick it from the metadata.
Or using the website will do too.
But title still use filename instead of metadata. The issue is still ongoing.
May be we should report this, I'm sure a lot of people already have done that.

In the mean time, we need to use a meaningful filename here.

I think I will test the mobi conversion with kindlegen or kindle previewer, and put the file on device directly to see how it behave.
If it's better, I will add a section in the readme.

**Comment by yoanhg421** [comment]
OK. I made the changes. 
Sorry about that. I'm new to contributing.

**Comment by yoanhg421** [comment]
If you try kindlegen, I was doing some testing and it seems to error out on files that are really big
I had a successful 800MB but it failed on a 1.2GB and above. I think that's why KCC splits @ ~400MB

**Comment by celogeek** [comment]
you have close this pr and create this one https://github.com/celogeek/go-comic-converter/pull/9
And yes mobi is limited, so you may need to limit the size to 400mb to use it.

**Pull request closed without merging**
