### PR TITLE
Fix display on Kobo, epub

### PR DESCRIPTION
**Pull request by yoanhg421**

### CODE REVIEW

**Comment by yoanhg421** [comment]
You want to add the colors  back to the styles I just realized it will look weird if you have dark mode enabled on the Scribe. 
I don;t think kobo has a dark mode. at least the Libra 2 doesn't, but maybe the Sage does, or they might add it in the future.
```
body{
  color: #{{ .View.Color.Foreground }};
  background: #{{ .View.Color.Background }};
}

```

**Comment by yoanhg421** [comment]
looks like the kindle automatically spreads double pages in landscape mode. you don't have to spread them yourself. 
no blank pages to mess with and no gaps. 
the top and bottom margin on double pages, some have them, some don't, it depends on the scan.

This is the result. 

```
[Log] Go Comic Converter (Main.vue, line 126)

Options:
    Author                          : Comic Converter
    Title                           : Kill la Kill
    Workers                         : 10
    Profile                         : KS - Kindle Scribe - 1860x2480
    Format                          : jpeg
    Quality                         : 80
    Grayscale                       : false
    Crop                            : true
    Crop Ratio                      : 1 Left - 1 Up - 1 Right - 3 Bottom
    Auto Contrast                   : false
    Auto Rotate                     : false
    Auto Split DoublePage           : false
    No Blank Image                  : true
    Manga                           : true
    Has Cover                       : false
    Limit                           : 500 Mb
    Strip First Directory From Toc  : true
    Sort Path Mode                  : path=alphanum, file=alpha
    Foreground Color                : #000
    Background Color                : #FFF
    Resize                          : true
    Portrait Only                   : false
    Title Page                      : never
    Apple Book Compatibility        : false


Completed in 9.538s, Memory usage 629 Mb
```

With 1.6 Aspect Ratio
IMG_5070
IMG_5071
IMG_5072

With -1 Aspect Ratio

IMG_5073
IMG_5074
IMG_5075

**Comment by yoanhg421** [comment]
Ok. so after a lot of testing. these are the best styles 

The first commit is for Kobo
Kobo only needs the View.Height height set on the css.
if you set the width the image will fill the screen but stretched. Honestly. it doesn't look bad. 
Also non-rotated double pages will squeeze into the screen. best results is to rotate, or split and not keep original. 

Kindle PW and Scribe work well with the second commit it needs the image width and heigh set on the img tag. no split, no rotate, no portrait or landscape. see the settings above.

I want to pass the Viewport dimensions to the image width and height and test if it makes a difference. 
Also the different ratios show different gaps. 1.33 works pretty well. 
I'm sure there is a way to get the perfect ratio.

**Comment by yoanhg421** [comment]
IMG_5080
IMG_5079
IMG_5078
IMG_5077

**Comment by yoanhg421** [comment]
By the way landscape doesn't work properly on the kobo. it only shows one image. and it gets cut-off. kcc doesnt work either.

**Comment by celogeek** [comment]
The patch finally remove the Top alignment. This is used to vertical align the image.

The current setup set the View Port to the one of the device, with the ratio applied.
For example with SR profile (1860x2480) and ratio 1:1.6, then View Port = 1550x2480.

Amazon advice the ratio 1.6 for their device for best rendering in all situation. If I use the device ratio, it works well on portrait but badly on landscape. Only 1.6 cover both.

So then, each image is resize to fit into this view port. Usually the Width = View.Width and Height is a little bit smaller, so I center on page using Top alignment. Otherwise it's push to the top with a big band on the bottom.
In case I have to use the Height, the the text-align: center should place the screen in the middle.

Here:
```
  -aspect-ratio float (default 1.6)
    	Aspect ratio (height/width) of the output
    	 -1 = same as device
    	  0 = same as source
    	1.6 = amazon advice for kindle
```

So in you case, I would want you to test on Kobo:
```
--portrait-only --aspect-ratio=-1 --autosplitdoublepage --keepdoublepageifsplitted=false --profile KoS
```
And if you prefer having the double page uncut but rotated:
```
--portrait-only --aspect-ratio=-1 --autosplitdoublepage=false --profile KoS --autorotate
```

And to keep the original image entirely, remove the crop:
```
--crop=false
```

KCC doesn't support Landscape last time I check (long time ago), that's why my CSS and organisation differ from it. The code I generate is compatible with landscape by default.

So I inject blank page when needed, but make it invisible on portrait (work only on kindle device).
Each page spread to right, need a page spread to left before you add a new one spread to center.

This spread behaviour is removed on portrait-only mode, as it's not need.

So it may be useful that I implement capacity on each type of device to automatically set some settings like aspect ratio, portrait only, ...

Can you try those settings with the branch I create (so please keep the Top css, it's important), and also on the master branch. I want to know if it actually work fine without any changes or with the new style only.

**Comment by celogeek** [comment]
About the space between images on landscape,

When I have a perfect ratio for Amazon of the view port, it mean I have 2 windows of the perfect size near each other.
But amazon doesn't glue them it seems. 
So I place the images in the view port, and they take the full width of the view port.
So if amazon glue them, it should be visible, but no. So it means they left some space here.

When I disconnect the image using absolute position, it's kind of floating above the body, and so when I use the left or right alignment, it go to the left or right of the window itself, and I suspect it is outside the size of the body.
So it appear like glue together on landscape.

I will try to use the new style, but align left/right to compare.

**Comment by yoanhg421** [comment]
The first set of images above is the Kindle Scribe with aspect ration of -1.  And ,no rotate ,no split.  With the styles in the patch.  Try it out.  I think it looks pretty good. 

Double pages spread nicely and with no gap.  

Second set of images is how it looks in the Kobo. 

Kobo reader seems old.  Needs different css and html. And the ncx file.

**Comment by yoanhg421** [comment]
Hey. so you don't have to worry about this anymore.
I found out the best way to read manga in a Kobo is to install KoReader and make a CBZ of the manga folder. 
It even automatically crops margins for you and it's very fast.
 
Kobo only supports epub2 so LTR doesn't work right either. You have to use KoReader for epub3 anyways

KoReader is the best solution for Manga on Kobo.
GoComicConverter is the best solution for Kindles.

**Pull request closed without merging**
